package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"time"
)

var MunicipiD = "08073"
var ApiKey = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZ2lyYmF1QG91dGxvb2suZXMiLCJqdGkiOiIxMGIzYTAzNS0zOGRlLTQ5YjEtOWU1OS02ODAyNGE0NGZhNGMiLCJleHAiOjE3OTMzNzI0NjQsImlzcyI6IkFFTUVUIiwiaWF0IjoxNzg0NzMyNDY0LCJ1c2VySWQiOiIxMGIzYTAzNS0zOGRlLTQ5YjEtOWU1OS02ODAyNGE0NGZhNGMiLCJyb2xlIjoiIn0.k79xtYa9f8jgboa_ScKF1DyRLcNl_9K1JE8xw1cAT28"

type primeraCrida struct {
	Url string `json:"datos"`
}

type AutoGenerated []struct {
	Origen     Origen     `json:"origen"`
	Elaborado  string     `json:"elaborado"`
	Nombre     string     `json:"nombre"`
	Provincia  string     `json:"provincia"`
	Prediccion Prediccion `json:"prediccion"`
	ID         int        `json:"id"`
	Version    float64    `json:"version"`
}

type Origen struct {
	Productor string `json:"productor"`
	Web       string `json:"web"`
	Enlace    string `json:"enlace"`
	Language  string `json:"language"`
	Copyright string `json:"copyright"`
	NotaLegal string `json:"notaLegal"`
}

type ProbPrecipitacion struct {
	Value   int    `json:"value"`
	Periodo string `json:"periodo"`
}

type Dato struct {
	Value int `json:"value"`
	Hora  int `json:"hora"`
}

type Temperatura struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}

type HumedadRelativa struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}

type Dia struct {
	ProbPrecipitacion []ProbPrecipitacion `json:"probPrecipitacion"`
	Temperatura       Temperatura         `json:"temperatura"`
	HumedadRelativa   HumedadRelativa     `json:"humedadRelativa"`
	Fecha             string              `json:"fecha"`
}

type Prediccion struct {
	Dia []Dia `json:"dia"`
}

type Diaria struct {
	ProbPrecipitacio int       `json:"probPrecipitacion"`
	TemperaturaMax   int       `json:"maxima"`
	TemperaturaMin   int       `json:"minima"`
	HumitatRelativa  int       `json:"humedadRelativa"`
	Time             time.Time `json:"-"`
	Ciutat           string    `json:"nombre"`
	TempHores        []Dato    `json:"-"`
}

func (diaria *Diaria) GetPrevisions() (*Diaria, error) {
	url, err := primeraInvocacio(MunicipiD)
	if err != nil {
		return nil, err
	}
	return segonaInvocacio(url)
}

func primeraInvocacio(codiMunicipi string) (string, error) {
	if len(codiMunicipi) == 3 {
		codiMunicipi = "08" + codiMunicipi
	}

	url := fmt.Sprintf("https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/%s/?api_key=%s", codiMunicipi, ApiKey)

	peticio, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return "", err
	}
	peticio.Header.Add("cache-control", "no-cache")

	res, err := http.DefaultClient.Do(peticio)
	if err != nil {
		log.Println("error comunicant amb AEMET", err)
		return "", err
	}
	defer res.Body.Close()

	cos, err := io.ReadAll(res.Body)
	if err != nil {
		log.Println("error llegint el cos de la resposta")
		return "", err
	}

	contenidor := primeraCrida{}
	err = json.Unmarshal(cos, &contenidor)

	if err != nil || contenidor.Url == "" {
		log.Printf("AVÍS AEMET (Codi HTTP %d): %s\n", res.StatusCode, string(cos))
		return "", fmt.Errorf("error en la resposta de l'AEMET o límit superat")
	}

	return contenidor.Url, nil
}

func segonaInvocacio(url string) (*Diaria, error) {
	peticio, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}

	peticio.Header.Add("cache-control", "no-cache")

	res, err := http.DefaultClient.Do(peticio)
	if err != nil {
		log.Println("error comunicant amb AEMET", err)
		return nil, err
	}
	defer res.Body.Close()

	cos, err := io.ReadAll(res.Body)
	if err != nil {
		log.Println("error llegint el cos de la resposta")
		return nil, err
	}

	previsio := AutoGenerated{}
	err = json.Unmarshal(cos, &previsio)
	if err != nil {
		log.Println("error decodificant el json unmarshalling")
		return nil, err
	}

	if len(previsio) == 0 || len(previsio[0].Prediccion.Dia) == 0 {
		return nil, fmt.Errorf("la resposta de l'AEMET no conté dades de predicció")
	}

	d := previsio[0].Prediccion.Dia[0]

	precipitacio := 0
	if len(d.ProbPrecipitacion) > 0 {
		precipitacio = d.ProbPrecipitacion[0].Value
	}

	valors := Diaria{
		ProbPrecipitacio: precipitacio,
		TemperaturaMax:   d.Temperatura.Maxima,
		TemperaturaMin:   d.Temperatura.Minima,
		HumitatRelativa:  d.HumedadRelativa.Maxima,
		Time:             time.Now(),
		Ciutat:           previsio[0].Nombre,
		TempHores:        d.Temperatura.Dato,
	}

	return &valors, nil
}

func ObtenirPrevisionsMultiDiaria() ([]Dia, string, error) {
	url, err := primeraInvocacio(MunicipiD)
	if err != nil {
		return nil, "", err
	}

	peticio, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, "", err
	}
	peticio.Header.Add("cache-control", "no-cache")

	res, err := http.DefaultClient.Do(peticio)
	if err != nil {
		log.Println("error comunicant amb AEMET", err)
		return nil, "", err
	}
	defer res.Body.Close()

	cos, err := io.ReadAll(res.Body)
	if err != nil {
		log.Println("error llegint el cos de la resposta")
		return nil, "", err
	}

	var previsio AutoGenerated
	err = json.Unmarshal(cos, &previsio)
	if err != nil {
		log.Println("error decodificant el json unmarshalling")
		return nil, "", err
	}

	if len(previsio) == 0 {
		return nil, "", nil
	}

	return previsio[0].Prediccion.Dia, previsio[0].Nombre, nil
}
